---
title: "table"
author: "Hyeonjin Kim"
date: "11/9/2021"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
# https://cran.r-project.org/web/packages/arsenal/vignettes/tableby.html

knitr::opts_chunk$set(echo = TRUE)
library(arsenal)
setwd("/home/kimhj9502/Project/project_tDCS/analysis/survey_1stonly/")
```

```{r cars}
results="asis"
demo = read.csv('demo_concat.csv' , header=T)
table_one <- tableby(anode ~ age + male, data = demo) 
summary(table_one)
```

```{r cars}
results="asis"
demo = read.csv('demo_concat.csv' , header=T)
table_one <- tableby(anode ~ SCID_avoidant+SCID_dependent+SCID_obsessive.compulsive+SCID_passive.aggressive+SCID_depressive+SCID_paranoid+SCID_schizotypal + SCID_schizoid+SCID_histrionic+SCID_narcissistic+SCID_borderline+SCID_antisocial, data = demo) 
summary(table_one)
```
```{r cars}
results="asis"
demo = read.csv('demo_concat.csv' , header=T)
table_one <- tableby(anode ~ Y.BOCS_O+Y.BOCS_C+BDI_total+STAI.X.1_total+STAI.X.2_total+BIS11_C+BIS11_M+BIS11_P, data = demo) 
summary(table_one)
```








